### PR TITLE
merge for 528 fix

### LINKED ISSUE #528: Customer Source Provider Overlay Footprint
Check footprint geo.json type and if Polygon convert to MultiPolygon

### PR DESCRIPTION
**Pull request by asafMasa**
#528

### CODE REVIEW

File: src/app/packages/core/utils/geo.ts [hunk 1]
```diff
@@ -22,3 +22,27 @@ export function getPointByPolygon(geometry: GeometryObject | FeatureCollection<a
 		return <Point>centerOfMass(feature(<GeometryObject>geometry)).geometry;
 	}
 }
+
+export  function geojsonMultiPolygonToPolygon(multiPolygon: MultiPolygon): Polygon {
+	if (!multiPolygon) {
+		return null;
```
Comment (AmitMY) [inline src/app/packages/core/utils/geo.ts]: do you need `null` specifically or can this be `return;`?

File: src/app/packages/core/utils/geo.ts [hunk 2]
```diff
@@ -22,3 +22,27 @@ export function getPointByPolygon(geometry: GeometryObject | FeatureCollection<a
...
+
+	return {
+		type: "Polygon",
+		coordinates: multiPolygon.coordinates[0]
+	};
+}
+
+export  function geojsonPolygonToMultiPolygon(polygon: Polygon): MultiPolygon {
+	if (!polygon) {
+		return null;
```
Comment (AmitMY) [inline src/app/packages/core/utils/geo.ts]: do you need `null` specifically or can this be `return;`?

File: src/app/packages/core/utils/geo.ts [hunk 3]
```diff
@@ -22,3 +22,27 @@ export function getPointByPolygon(geometry: GeometryObject | FeatureCollection<a
 		return <Point>centerOfMass(feature(<GeometryObject>geometry)).geometry;
 	}
 }
+
+export  function geojsonMultiPolygonToPolygon(multiPolygon: MultiPolygon): Polygon {
```
Comment (AmitMY) [inline src/app/packages/core/utils/geo.ts]: function has no tests, and is not used

File: src/app/packages/core/utils/geo.ts [hunk 4]
```diff
@@ -22,3 +22,27 @@ export function getPointByPolygon(geometry: GeometryObject | FeatureCollection<a
...
+		return null;
+	}
+
+	return {
+		type: "Polygon",
+		coordinates: multiPolygon.coordinates[0]
+	};
+}
+
+export  function geojsonPolygonToMultiPolygon(polygon: Polygon): MultiPolygon {
```
Comment (AmitMY) [inline src/app/packages/core/utils/geo.ts]: function has no tests, and is not used

**Comment by AmitMY** [comment]
@asafMasa Unfortunately, Ohad merged just before I sent my review, but I do want you to address my comments.
