### PR TITLE
Change text on imagery-status + fix "back to world view" 

### LINKED ISSUE #359: Bug: (Customer site) Back to world doesn't clean overlay from backend
* **Reproduce:**
1. Select a case
2. Open overlay in map 1
3. Press Back to world
4. Refresh (F5) the app

* **Expected:**
world view is loaded

* **Actual:**
App loads last overlay

### LINKED ISSUE #368: Change text on imagery-status and status-bar.
- [ ] Change displayed text from overlay name to sensor type and date.
- [ ] fix back to world view from status-bar. (sending active_map_id and update case)

### PR DESCRIPTION
**Pull request by yairtawil**
Change text on imagery-status,
resolve #368 
resolve #359

### CODE REVIEW

File: src/app/ansyn/ansyn.component.ts [hunk 1]
```diff
@@ -44,14 +44,21 @@ export class AnsynComponent implements OnInit{
...
 			return sum;
-	});
+		});
+
+
+	displayedOverlay$ = this.store.select('cases')
+		.filter((cases: ICasesState) => !isNil(cases.selected_case))
+		.map((cases: ICasesState) => {
+			const activeMap: CaseMapState = cases.selected_case.state.maps.data.find((map) => map.id == cases.selected_case.state.maps.active_map_id);
+			return activeMap.data.selectedOverlay;
```
Comment (MarkShleifer) [inline src/app/ansyn/ansyn.component.ts]: Please change selectedOverlay to overlay

File: src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.html [hunk 2]
```diff
@@ -1,17 +1,16 @@
...
-
-
-
 		<div class='map-container-wrapper' *ngIf="maps.data[index]" (click)="changeActiveImagery(maps.data[index].id)">
-			<ansyn-imagery-container class="map" [mapComponentSettings]="maps.data[index]" [active]="maps.active_map_id == maps.data[index].id" [show-status]="count > 1" [showSpinner]="isOverlayLoading((maps.data[index].data.selectedOverlay)?.id)" ></ansyn-imagery-container>
+			<ansyn-imagery-container class="map"
+									 [map-state]="maps.data[index]"
+									 [active]="maps.active_map_id == maps.data[index].id"
+									 [show-status]="count > 1"
+									 [overlay]="maps.data[index].data.selectedOverlay"
```
Comment (MarkShleifer) [inline src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.html]: overlay is a redundant  input

File: src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.ts [hunk 3]
```diff
@@ -1,14 +1,13 @@
...
 import { CaseMapState } from '@ansyn/menu-items/cases';
 import { range } from 'lodash';
 import { MapEffects } from '../../effects/map.effects';
 import { ImageryCommunicatorService } from '@ansyn/imagery';
-import { isEmpty } from 'lodash';
 import { Observable } from 'rxjs/Observable';
-import { SetLoadingOverlaysAction } from '../../actions/map.actions';
 import { Store } from '@ngrx/store';
 import { IMapState } from '../../reducers/map.reducer';
+import { CaseMapsState } from '../../../core/models/case.model';
```
Comment (MarkShleifer) [inline src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.ts]: import from core please

File: src/app/packages/map-facade/components/imagery-container/imagery-container.component.ts [hunk 4]
```diff
@@ -1,19 +1,20 @@
...
 })
 export class ImageryContainerComponent implements OnInit, AfterViewInit, OnDestroy {
-	@Input() mapComponentSettings: ImageryComponentSettings;
+	@Input('map-state') mapState: CaseMapState;
 	@Input() active: boolean;
 	@Input('show-status') showStatus: boolean;
 
 	@ViewChild('imageryViewContainer') imageryViewContainer: ElementRef;
 	private _showSpinner: boolean;
+	@Input() overlay;
```
Comment (MarkShleifer) [inline src/app/packages/map-facade/components/imagery-container/imagery-container.component.ts]: redundant?

**Comment by MarkShleifer** [comment]
Please consider writing a common component which displays the overlays sensor name and date, due to the fact that this functionality is used twice in our application.
