### PR TITLE
#138 #187 Integration fix

### LINKED ISSUE #138: Insert and integrate code with G
#207

### PR DESCRIPTION
**Pull request by asafMasa**
#138
 #187

### CODE REVIEW

File: src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts [hunk 1]
```diff
@@ -48,12 +48,48 @@ export class OpenLayerMap implements IMap {
...
+		//this._mapObject.getLayers().clear();
 		this._mapLayers.forEach((existingLayer) => {
 			this._mapObject.removeLayer(existingLayer);
 		});
+		this._mapLayers = [];
 
-		this._mapLayers = [layer];
-		this._mapObject.addLayer(layer);
+		const currentZoom = this._mapObject.getView().getZoom();
+		const currentCenter = this._mapObject.getView().getCenter();
```
Comment (yairtawil) [inline src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts]: add currentRotation

File: src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts [hunk 2]
```diff
@@ -16,31 +16,40 @@ export class OpenLayerMap implements IMap {
 	public centerChanged: EventEmitter<GeoJSON.Point>;
 	public positionChanged: EventEmitter<Position>;
 
-	constructor(element: HTMLElement, layers: any) {
+	constructor(element: HTMLElement, layers: any, position: Position) {
```
Comment (yairtawil) [inline src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts]: position?: Position 🔢

File: src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts [hunk 3]
```diff
@@ -16,31 +16,40 @@ export class OpenLayerMap implements IMap {
...
 		this._mapType = 'openLayerMap';
 		this.centerChanged = new EventEmitter<GeoJSON.Point>();
 		this.positionChanged = new EventEmitter<Position>();
-		this.initMap(element, layers);
+		this.initMap(element, layers, position);
 	}
 
-	private initMap(element: HTMLElement, layers: any) {
+	private initMap(element: HTMLElement, layers: any,  position: Position) {
```
Comment (yairtawil) [inline src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts]: position?: Position 🔢
