### PR TITLE
fix(context-menu): enabled buttons are falsely enabled

### LINKED ISSUE #687: context menu on base map - enable "prev" and "first" buttons
Current:
1. display overlays
2. open context menu in the area of an overlay
3. only "next' "last" and "best" options are enabled

Ecpected:
1. display overlays
2. open context menu in the area of an overlay
3. **prev, first,**"next' "last" and "best" options are enabled
4. pressing "first" - first overlay in context will be presented
5. pressing "prev" - first overlay in context will be presented

### LINKED ISSUE #690: context menu enabled buttons are falsely enabled
reproduction:
1. open: https://goo.gl/bzN2Fp
2. right click on an area with more then 2 overlays
3. right-click on an area with no overlays - next, prev, first, last, best buttons are enabled (shouldn't be..)

### PR DESCRIPTION
**Pull request by yairtawil**
resolve #690 
resolve #687

### CODE REVIEW

File: src/app/packages/map-facade/components/context-menu/context-menu.component.ts [hunk 1]
```diff
@@ -127,25 +167,20 @@ export class ContextMenuComponent implements OnInit {
...
-
-		if (this.displayedOverlayIndex === -1) {
-			if (_isNil(this.displayedOverlay)) {
-				this.prevSensors = [];
-				this.nextSensors = Array.from(this.allSensors);
-			}
+	}
+
+	initializeSensors(filteredOverlays, displayedOverlayDate?) {
+		if (!displayedOverlayDate) {
```
Comment (AmitMY) [inline src/app/packages/map-facade/components/context-menu/context-menu.component.ts]: use `displaedOverlay` instead, in else initialize date

File: src/app/packages/map-facade/components/context-menu/context-menu.component.ts [hunk 2]
```diff
@@ -158,25 +193,24 @@ export class ContextMenuComponent implements OnInit {
...
 
 	clickBest($event: MouseEvent, subFilter?: string) {
-		const sensorOnly = this.filteredOverlays.filter((overlay: Overlay) => !subFilter || subFilter === overlay[this.filterField]);
-		const bestOverlay = sensorOnly.reduce((minValue, value) => {
-			return value.bestResolution < minValue.bestResolution ? value : minValue;
-		});
+		const sensorOnly = this.filteredOverlays
+			.filter((overlay: Overlay) => !subFilter || subFilter === overlay[this.filterField]);
+		const bestOverlay = sensorOnly
+			.reduce((minValue, value) => {
```
Comment (AmitMY) [inline src/app/packages/map-facade/components/context-menu/context-menu.component.ts]: reduce this
