### PR TITLE
fix(menu): Menu state should be saved ( sessionStorage )

### LINKED ISSUE #657: Menu state should be saved ( sessionStorage ).
Menu state should include:
 - selected menu item (`String`)
 - Is pinned  (`Boolean`)

### PR DESCRIPTION
**Pull request by yairtawil**
resolve #657

### CODE REVIEW

File: src/app/packages/menu/menu/menu.component.ts [hunk 1]
```diff
@@ -92,19 +112,35 @@ export class MenuComponent implements OnInit {
...
-			if (_isPinned) {
-				this.renderer.addClass(this.container.nativeElement, 'pinned');
-			} else {
-				this.renderer.removeClass(this.container.nativeElement, 'pinned');
-			}
-			this.store.dispatch(new ContainerChangedTriggerAction());
+			this.onIsPinnedChange();
+		});
+
+		this.clickOutside$.subscribe((clickOutside: boolean) => {
```
Comment (AmitMY) [inline src/app/packages/menu/menu/menu.component.ts]: put subscribers in onInit
